import { StyleSheet } from 'react-native';
import { FontFamily } from '@/styles/ui-theme';

const fontFamily = FontFamily.cairo;

export const styles = StyleSheet.create({
  heroShell: {
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
  },
  hero: {
    overflow: 'hidden',
    minHeight: 168,
    paddingTop: 22,
    paddingHorizontal: 24,
    paddingBottom: 52,
  },
  heroGlow: {
    position: 'absolute',
    top: -124,
    right: -28,
    width: 248,
    height: 248,
    borderRadius: 140,
    opacity: 0.46,
  },
  heroTint: {
    ...StyleSheet.absoluteFillObject,
  },
  backButton: {
    position: 'absolute',
    top: 30,
    left: 22,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    zIndex: 3,
    elevation: 3,
  },
  heroBrandRow: {
    minHeight: 112,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  shieldWrap: {
    width: 58,
    height: 58,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  heroTextWrap: {
    alignItems: 'flex-end',
    marginTop: 2,
  },
  heroTitle: {
    color: '#ffffff',
    fontFamily,
    fontSize: 24,
    fontWeight: '900',
  },
  heroSubtitle: {
    fontFamily,
    marginTop: 3,
    fontSize: 14,
    fontWeight: '600',
  },
  heroCurve: {
    position: 'absolute',
    left: '-18%',
    width: '136%',
    bottom: -122,
    height: 136,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
  },
  tabsWrap: {
    marginTop: -14,
    paddingHorizontal: 0,
  },
  tabsRail: {
    width: '100%',
    borderRadius: 21,
    borderWidth: 1,
    overflow: 'hidden',
  },
  tabsScroller: {
    width: '100%',
  },
  tabsContent: {
    flexDirection: 'row-reverse',
    minWidth: '100%',
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  tabsContentCompact: {
    flexGrow: 1,
  },
  tabButton: {
    minHeight: 46,
    borderRadius: 16,
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  tabText: {
    fontFamily,
    fontSize: 12,
    fontWeight: '700',
  },
  toast: {
    minHeight: 56,
    borderRadius: 20,
    marginTop: 18,
    marginHorizontal: 16,
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
    paddingHorizontal: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  toastText: {
    flex: 1,
    color: '#ffffff',
    textAlign: 'right',
    fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  card: {
    borderWidth: 1,
    borderRadius: 30,
    padding: 18,
  },
  metricCard: {
    flex: 1,
    minHeight: 168,
  },
  metricTopRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metricIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trendPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  trendText: {
    fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  metricValue: {
    marginTop: 34,
    textAlign: 'right',
    fontFamily,
    fontSize: 26,
    fontWeight: '900',
  },
  metricLabel: {
    marginTop: 4,
    textAlign: 'right',
    fontFamily,
    fontSize: 13,
    fontWeight: '700',
  },
  quickAction: {
    minHeight: 82,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  quickActionLeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  quickActionText: {
    fontFamily,
    fontSize: 16,
    fontWeight: '700',
  },
  quickActionIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  panelHeadingTextWrap: {
    alignItems: 'flex-end',
  },
  panelTitle: {
    fontFamily,
    fontSize: 18,
    fontWeight: '900',
  },
  panelSubtitle: {
    fontFamily,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  panelAction: {
    fontFamily,
    fontSize: 14,
    fontWeight: '700',
  },
  searchWrap: {
    minHeight: 58,
    marginTop: 12,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontFamily,
    fontSize: 15,
    fontWeight: '700',
  },
  badge: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  badgeText: {
    fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  badgeCompact: {
    minHeight: 24,
    paddingHorizontal: 10,
  },
  badgeTextCompact: {
    fontSize: 10.5,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 18,
    paddingHorizontal: 20,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  primaryButtonText: {
    fontFamily,
    fontSize: 16,
    fontWeight: '900',
  },
  outlinedStat: {
    width: '100%',
    minHeight: 92,
    borderRadius: 24,
    borderWidth: 2,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  outlinedStatPressable: {
    width: '100%',
  },
  outlinedStatValue: {
    textAlign: 'center',
    fontFamily,
    fontSize: 18,
    fontWeight: '900',
  },
  outlinedStatTitle: {
    textAlign: 'center',
    fontFamily,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 14,
  },
  sheetAvoider: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  confirmBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  sheet: {
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    maxHeight: '90%',
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingTop: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 54,
    height: 5,
    borderRadius: 999,
    marginBottom: 14,
  },
  sheetClose: {
    position: 'absolute',
    top: 24,
    right: 18,
    zIndex: 10,
  },
  sheetCloseText: {
    fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  sheetTitle: {
    textAlign: 'center',
    fontFamily,
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 12,
  },
  sheetContent: {
    width: '100%',
    paddingBottom: 24,
    gap: 16,
  },
  confirmCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    borderRadius: 34,
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    overflow: 'hidden',
  },
  confirmIconWrap: {
    width: 84,
    height: 84,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmTitle: {
    marginTop: 14,
    textAlign: 'center',
    fontFamily,
    fontSize: 20,
    fontWeight: '900',
  },
  confirmSubtitle: {
    marginTop: 6,
    textAlign: 'center',
    fontFamily,
    fontSize: 16,
    fontWeight: '700',
  },
  confirmDescription: {
    marginTop: 8,
    textAlign: 'center',
    fontFamily,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 24,
  },
  confirmActions: {
    flexDirection: 'row-reverse',
    gap: 14,
    marginTop: 22,
    width: '100%',
  },
  confirmButtonHalf: {
    flex: 1,
  },
  tabHovered: {
    opacity: 0.84,
  },
  hoveredLift: {
    transform: [{ translateY: -1 }],
  },
  fieldWrap: {
    gap: 6,
  },
  fieldLabel: {
    textAlign: 'right',
    fontFamily,
    fontSize: 14,
    fontWeight: '700',
  },
  fieldShell: {
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
  },
  fieldInput: {
    flex: 1,
    fontFamily,
    fontSize: 15,
    fontWeight: '700',
  },
  fieldError: {
    textAlign: 'right',
    fontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
    minHeight: 18,
  },
  selectAnchor: {
    position: 'relative',
    zIndex: 20,
  },
  selectShell: {
    minHeight: 58,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  selectValue: {
    flex: 1,
    textAlign: 'right',
    fontFamily,
    fontSize: 15,
    fontWeight: '700',
  },
  selectMenu: {
    marginTop: 10,
    borderRadius: 22,
    borderWidth: 1,
    overflow: 'hidden',
  },
  selectOption: {
    minHeight: 52,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  selectOptionText: {
    textAlign: 'right',
    fontFamily,
    fontSize: 15,
    fontWeight: '700',
  },
  segmentedWrap: {
    width: '100%',
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  segmentOption: {
    minHeight: 56,
    borderRadius: 20,
    borderWidth: 2,
    paddingHorizontal: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  segmentText: {
    fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  switchCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  switchTextWrap: {
    flex: 1,
    alignItems: 'flex-end',
  },
  switchTitle: {
    fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  switchSubtitle: {
    fontFamily,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  switchIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadWrap: {
    minHeight: 250,
    borderRadius: 28,
    borderWidth: 2,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  uploadImage: {
    width: '100%',
    height: 220,
    borderRadius: 18,
  },
  uploadIcon: {
    width: 70,
    height: 70,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadTitle: {
    marginTop: 16,
    fontFamily,
    fontSize: 22,
    fontWeight: '800',
  },
  uploadHint: {
    marginTop: 6,
    fontFamily,
    fontSize: 14,
    fontWeight: '600',
  },
  uploadButton: {
    marginTop: 16,
    minHeight: 42,
    borderRadius: 999,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadButtonText: {
    fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  emptyCard: {
    alignItems: 'center',
    paddingVertical: 34,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    marginTop: 12,
    fontFamily,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyDescription: {
    marginTop: 8,
    textAlign: 'center',
    fontFamily,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 22,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
});
