import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  accessStateScreen: {
    backgroundColor: '#f3f5fb',
  },
  accessStateContainer: {
    flex: 1,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessStateCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 30,
    paddingHorizontal: 22,
    paddingVertical: 26,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.06)',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 6,
    gap: 12,
  },
  accessStateEyebrow: {
    color: '#8a94a6',
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 13,
    fontWeight: '800',
  },
  accessStateTitle: {
    color: '#111827',
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 24,
    fontWeight: '900',
  },
  accessStateMessage: {
    color: '#475569',
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 28,
  },
  accessStateButton: {
    minHeight: 52,
    marginTop: 4,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2f67ea',
  },
  accessStateButtonText: {
    color: '#ffffff',
    fontFamily: 'Cairo',
    fontSize: 15,
    fontWeight: '800',
  },
  root: {
    flex: 1,
  },
  content: {
    paddingBottom: 32,
    alignItems: 'center',
  },
  sectionWrap: {
    width: '100%',
    maxWidth: 620,
    paddingHorizontal: 16,
    gap: 16,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  metricsSingle: {
    width: '49%',
    alignSelf: 'flex-end',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 12,
  },
  summaryCell: {
    width: '48.5%',
  },
  rolesSummaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 12,
  },
  rolesSummaryCell: {
    flex: 1,
  },
  summaryGridWide: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
    marginTop: 12,
  },
  summaryWideCell: {
    flex: 1,
  },
  stack: {
    gap: 10,
    marginTop: 6,
  },
  addDashed: {
    minHeight: 68,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  addDashedText: {
    fontFamily: 'Cairo',
    fontSize: 18,
    fontWeight: '800',
  },
  fieldSection: {
    gap: 8,
  },
  sectionLabel: {
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 14,
    fontWeight: '700',
  },
  inlineError: {
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 12,
    fontWeight: '700',
    marginTop: -6,
  },
  previewHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  previewHeaderText: {
    fontFamily: 'Cairo',
    fontSize: 14,
    fontWeight: '800',
  },
  previewTitle: {
    marginTop: 14,
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 18,
    fontWeight: '900',
  },
  previewMeta: {
    marginTop: 6,
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 13,
    fontWeight: '600',
  },
  roleSheetBackdrop: {
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  roleSheet: {
    width: '100%',
    maxWidth: '100%',
    paddingHorizontal: 12,
  },
  roleSheetContent: {
    width: '100%',
    paddingBottom: 18,
    gap: 14,
  },
  permissionsCard: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 24,
  },
  permissionsTitle: {
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 6,
  },
  permissionsWrapLocal: {
    flexDirection: 'row-reverse',
    flexWrap: 'nowrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 4,
  },
  permissionChipText: {
    fontFamily: 'Cairo',
    fontSize: 10,
    fontWeight: '800',
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 999,
  },
  renewFloating: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 18,
  },
  renewLabel: {
    textAlign: 'right',
    fontFamily: 'Cairo',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 12,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
});
