import { StyleSheet } from 'react-native';
import { Colors, FontFamily, FontSize, FontWeight, SemanticColors } from '@/styles/ui-theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.primary },
  root: { flex: 1, backgroundColor: Colors.background },
  content: { backgroundColor: Colors.background },
  hero: { overflow: 'hidden', backgroundColor: Colors.primary },
  heroBg: { ...StyleSheet.absoluteFillObject, backgroundColor: Colors.primary },
  heroIn: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 36 },
  top: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  iconBtn: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)' },
  badge: { position: 'absolute', top: -3, right: -3, minWidth: 20, height: 20, borderRadius: 10, backgroundColor: SemanticColors.red, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderWidth: 2, borderColor: '#1d4ed8' },
  badgeTxt: { color: '#fff', fontFamily: FontFamily.cairo, fontSize: FontSize.xxs, fontWeight: FontWeight.bold },
  brand: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 },
  brandTxt: { alignItems: 'flex-end' },
  app: { color: '#fff', fontFamily: FontFamily.cairo, fontSize: FontSize.xl, fontWeight: FontWeight.extrabold, textAlign: 'right' },
  meta: { flexDirection: 'row-reverse', alignItems: 'center', gap: 6, marginTop: 2 },
  metaMuted: { color: 'rgba(255,255,255,0.55)', fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.medium },
  metaDot: { color: 'rgba(255,255,255,0.28)', fontSize: FontSize.x11 },
  metaStrong: { color: 'rgba(191,219,254,0.9)', fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.semibold },
  logoWrap: { width: 50, height: 50, borderRadius: 16, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,0.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  logo: { width: '100%', height: '100%' },
  heroCurve: {
    position: 'absolute',
    left: -8,
    right: -8,
    bottom: -20,
    height: 34,
    backgroundColor: Colors.background,
    borderTopLeftRadius: 42,
    borderTopRightRadius: 42,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.95)',
  },
  welcome: { alignItems: 'flex-end', marginBottom: 20 },
  welcomeSmall: { color: 'rgba(219,234,254,0.72)', fontFamily: FontFamily.cairo, fontSize: FontSize.md, fontWeight: FontWeight.medium, textAlign: 'right' },
  welcomeBig: { marginTop: 2, color: 'rgba(255,255,255,0.96)', fontFamily: FontFamily.cairo, fontSize: FontSize.lg, fontWeight: FontWeight.bold, textAlign: 'right' },
  search: { minHeight: 56, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', paddingHorizontal: 16 },
  searchIcon: { width: 32, height: 32, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.1)' },
  searchInput: { flex: 1, color: '#fff', fontFamily: FontFamily.cairo, fontSize: FontSize.md, writingDirection: 'rtl' },
  quickWrap: { marginTop: 18, paddingHorizontal: 16, zIndex: 3 },
  quickCard: { flexDirection: 'row-reverse', justifyContent: 'space-between', backgroundColor: Colors.card, borderRadius: 24, paddingHorizontal: 10, paddingVertical: 18, borderWidth: 1, borderColor: Colors.border, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.08, shadowRadius: 18, elevation: 6 },
  quickItem: { flex: 1, alignItems: 'center', gap: 10 },
  quickIcon: { width: 54, height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  quickTxt: { color: 'rgba(28,28,30,0.7)', fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.semibold, textAlign: 'center' },
  body: { paddingTop: 18, paddingHorizontal: 16 },
  ticker: { minHeight: 56, borderRadius: 18, paddingHorizontal: 16, backgroundColor: '#fff8ed', borderWidth: 1, borderColor: 'rgba(255,149,0,0.12)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  tickerIn: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10, flex: 1 },
  tickerText: { flex: 1 },
  tickerTitle: { color: '#c27200', fontFamily: FontFamily.cairo, fontSize: FontSize.md, fontWeight: FontWeight.bold, textAlign: 'right' },
  tickerIcon: { width: 32, height: 32, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,149,0,0.1)' },
  sec: { paddingTop: 20 },
  last: { paddingBottom: 8 },
  hRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  moreBtn: { flexDirection: 'row-reverse', alignItems: 'center', gap: 2 },
  moreTxt: { color: Colors.primary, fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.semibold },
  titleRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  titleTxt: { color: Colors.foreground, fontFamily: FontFamily.cairo, fontSize: FontSize.x17, fontWeight: FontWeight.bold },
  titleIcon: { width: 24, height: 24, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  rtlScroll: { transform: [{ scaleX: -1 }] },
  mirrorX: { transform: [{ scaleX: -1 }] },
  mirrorPressed: { transform: [{ scaleX: -1 }, { scale: 0.97 }] },
  hList: { paddingBottom: 2, paddingHorizontal: 6 },
  hCard: { marginHorizontal: 6 },
  vList: { gap: 8 },
  vGap: { marginTop: 8 },
  state: { minHeight: 112, borderRadius: 24, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, alignItems: 'center', justifyContent: 'center', gap: 10, paddingHorizontal: 18 },
  stateTxt: { color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.md, textAlign: 'center' },
  card: { borderRadius: 24, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 4 },
  newsCard: { width: 210, overflow: 'hidden' },
  newsTop: { height: 92, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', padding: 8 },
  newsImage: { ...StyleSheet.absoluteFillObject },
  emoji: { fontSize: 30 },
  newsBody: { paddingHorizontal: 14, paddingVertical: 14 },
  newsBadgeRow: { flexDirection: 'row-reverse', minHeight: 18, marginBottom: 8 },
  imp: { borderRadius: 8, backgroundColor: 'rgba(255,59,48,0.1)', paddingHorizontal: 6, paddingVertical: 2 },
  impTxt: { color: SemanticColors.red, fontFamily: FontFamily.cairo, fontSize: FontSize.xxs, fontWeight: FontWeight.bold },
  newsFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  serviceCard: { width: 248, padding: 18, overflow: 'hidden' },
  accent: { position: 'absolute', top: 0, right: 0, bottom: 0, width: 4 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pill: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  pillTxt: { fontFamily: FontFamily.cairo, fontSize: FontSize.xs, fontWeight: FontWeight.bold },
  softPill: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: Colors.secondary },
  softPillTxt: { color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.xs, fontWeight: FontWeight.semibold },
  cardTitle: { color: Colors.foreground, fontFamily: FontFamily.cairo, fontSize: FontSize.md, fontWeight: FontWeight.bold, textAlign: 'right', lineHeight: 22 },
  cardDesc: { marginTop: 6, marginBottom: 16, color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.sm, lineHeight: 21, textAlign: 'right' },
  footer: { borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  time: { flexDirection: 'row-reverse', alignItems: 'center', gap: 4 },
  timeTxt: { color: SemanticColors.green, fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.semibold },
  owner: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  ownerTxt: { color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.medium },
  avatar: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  avatarTxt: { color: '#fff', fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.bold },
  adCard: { width: 170, overflow: 'hidden' },
  media: { height: 128, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(120,120,128,0.06)', overflow: 'hidden', padding: 10 },
  adImage: { ...StyleSheet.absoluteFillObject },
  mediaEmoji: { fontSize: 40 },
  adPrice: { position: 'absolute', top: 12, left: 12, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.86)', paddingHorizontal: 10, paddingVertical: 4 },
  adPriceTxt: { color: SemanticColors.orange, fontFamily: FontFamily.cairo, fontSize: FontSize.xs, fontWeight: FontWeight.bold },
  adBody: { paddingHorizontal: 14, paddingVertical: 14 },
  adMeta: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'flex-end', gap: 6, marginTop: 6 },
  sep: { color: 'rgba(142,142,147,0.36)' },
  smallMuted: { color: 'rgba(142,142,147,0.7)', fontFamily: FontFamily.cairo, fontSize: FontSize.xxs },
  smallStrong: { color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.medium },
  offerCard: { width: 224, overflow: 'hidden' },
  offerTopBar: { height: 6 },
  offerBody: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },
  discount: { flexDirection: 'row-reverse', alignItems: 'center', gap: 2, borderRadius: 10, backgroundColor: 'rgba(255,59,48,0.1)', paddingHorizontal: 8, paddingVertical: 4 },
  discountTxt: { color: SemanticColors.red, fontFamily: FontFamily.cairo, fontSize: FontSize.xs, fontWeight: FontWeight.bold },
  offerType: { flexDirection: 'row-reverse', alignItems: 'center', gap: 4, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 },
  offerTypeTxt: { fontFamily: FontFamily.cairo, fontSize: FontSize.xs, fontWeight: FontWeight.bold },
  offerName: { marginTop: 12, color: Colors.foreground, fontFamily: FontFamily.cairo, fontSize: FontSize.md, fontWeight: FontWeight.extrabold, textAlign: 'right' },
  offerTitle: { marginTop: 4, fontFamily: FontFamily.cairo, fontSize: FontSize.sm, fontWeight: FontWeight.semibold, lineHeight: 20, textAlign: 'right' },
  offerFoot: { marginTop: 12, flexDirection: 'row-reverse', alignItems: 'center', gap: 4, justifyContent: 'flex-end' },
  offerFootTxt: { color: 'rgba(60,60,67,0.62)', fontFamily: FontFamily.cairo, fontSize: FontSize.xxs, fontWeight: FontWeight.semibold },
  event: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 14, borderRadius: 24, backgroundColor: '#fff', borderWidth: 1, borderColor: 'rgba(60,60,67,0.05)', padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 4 },
  eventDate: { alignItems: 'center' },
  dateBadge: { width: 56, height: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(175,82,222,0.08)' },
  dateMonth: { color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.x11, fontWeight: FontWeight.semibold },
  dateDay: { color: SemanticColors.violet, fontFamily: FontFamily.cairo, fontSize: FontSize.lg, fontWeight: FontWeight.extrabold, lineHeight: 26 },
  track: { width: 40, height: 4, borderRadius: 999, backgroundColor: Colors.secondary, overflow: 'hidden', marginTop: 8 },
  fill: { height: '100%', borderRadius: 999, backgroundColor: SemanticColors.violet },
  count: { marginTop: 4, color: Colors.mutedForeground, fontFamily: FontFamily.cairo, fontSize: FontSize.xxs },
  eventBody: { flex: 1 },
  eventMetaRow: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'flex-end', gap: 12, flexWrap: 'wrap' },
  metaItem: { flexDirection: 'row-reverse', alignItems: 'center', gap: 4 },
  fab: { position: 'absolute', left: 20, width: 56, height: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a84ff', shadowColor: '#0a84ff', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.28, shadowRadius: 16, elevation: 8 },
  pressed: { transform: [{ scale: 0.97 }] },
});
