import { StyleSheet } from 'react-native';
import { FontFamily } from '@/styles/ui-theme';

const fontFamily = FontFamily.cairo;

export const styles = StyleSheet.create({
  userCardRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  userActions: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
    flexShrink: 0,
  },
  userContent: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingLeft: 2,
  },
  entityRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 14,
  },
  entityBody: {
    paddingTop: 16,
  },
  entityMain: {
    flex: 1,
    alignItems: 'flex-end',
  },
  entityActions: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  entityFooterRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  footerActionRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  entityDivider: {
    height: 1,
    marginTop: 16,
    marginBottom: 14,
  },
  avatarSquare: {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatar: {
    flexShrink: 0,
    width: 56,
    height: 56,
    borderRadius: 18,
  },
  avatarText: {
    color: '#ffffff',
    fontFamily,
    fontSize: 28,
    fontWeight: '900',
  },
  userTitle: {
    textAlign: 'right',
    fontFamily,
    fontSize: 16,
    fontWeight: '900',
    flexShrink: 1,
  },
  userEmail: {
    marginTop: 5,
    textAlign: 'right',
    fontFamily,
    fontSize: 13,
    fontWeight: '600',
    width: '100%',
  },
  entityTitle: {
    textAlign: 'right',
    fontFamily,
    fontSize: 17,
    fontWeight: '900',
  },
  entityMeta: {
    marginTop: 6,
    textAlign: 'right',
    fontFamily,
    fontSize: 14,
    fontWeight: '600',
  },
  userHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
    width: '100%',
  },
  userMetaRow: {
    marginTop: 7,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    gap: 7,
    width: '100%',
  },
  userMetaText: {
    fontFamily,
    fontSize: 12.5,
    fontWeight: '600',
    flexShrink: 1,
    textAlign: 'right',
  },
  userPostsText: {
    flexShrink: 0,
  },
  userUniversityText: {
    maxWidth: '66%',
    lineHeight: 18,
  },
  userMetaSeparator: {
    fontFamily,
    fontSize: 12,
    fontWeight: '700',
    paddingTop: 1,
  },
  newsCard: {
    minHeight: 140,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  newsTopRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  newsActionRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  newsBadgeRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingTop: 2,
  },
  newsEditButton: {
    minHeight: 38,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  newsEditText: {
    fontFamily,
    fontSize: 13.5,
    fontWeight: '800',
  },
  newsDeleteButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  publishButton: {
    minHeight: 38,
    borderRadius: 18,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  publishButtonText: {
    color: '#ffffff',
    fontFamily,
    fontSize: 13.5,
    fontWeight: '800',
  },
  newsTitle: {
    marginTop: 22,
    textAlign: 'right',
    fontFamily,
    fontSize: 17,
    lineHeight: 31,
    fontWeight: '900',
  },
  newsMetaText: {
    marginTop: 0,
    textAlign: 'right',
    fontFamily,
    fontSize: 13.5,
    fontWeight: '600',
  },
  newsFooter: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  newsDate: {
    fontFamily,
    fontSize: 13.5,
    fontWeight: '600',
  },
  newsViewsRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
  },
  newsViewsText: {
    fontFamily,
    fontSize: 13.5,
    fontWeight: '600',
  },
  accentBar: {
    height: 4,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginHorizontal: -18,
  },
  actionButtonWide: {
    minHeight: 42,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionTextWide: {
    fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  permissionsWrap: {
    marginTop: 10,
    flexDirection: 'row-reverse',
    flexWrap: 'nowrap',
    gap: 3,
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
    overflow: 'hidden',
  },
  scopeWrap: {
    marginTop: 10,
    flexDirection: 'row-reverse',
    justifyContent: 'flex-end',
  },
  rolePermissionChip: {
    minHeight: 18,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 1,
  },
  rolePermissionText: {
    fontFamily,
    fontSize: 8,
    fontWeight: '800',
    lineHeight: 10,
  },
  roleMeta: {
    textAlign: 'left',
    fontFamily,
    fontSize: 12,
    fontWeight: '600',
  },
  offerHeaderRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  offerIdentity: {
    flex: 1,
    alignItems: 'flex-end',
    paddingTop: 2,
  },
  offerActionRow: {
    flexDirection: 'row-reverse',
    gap: 10,
    flexWrap: 'wrap',
  },
  offerBadges: {
    flexDirection: 'row-reverse',
    gap: 8,
  },
  offerHighlight: {
    marginTop: 12,
    borderRadius: 18,
    padding: 16,
  },
  offerHeadline: {
    textAlign: 'right',
    fontFamily,
    fontSize: 16,
    fontWeight: '900',
  },
  offerDescription: {
    marginTop: 6,
    textAlign: 'right',
    fontFamily,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 22,
  },
  offerMetaRow: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  offerMetaDetails: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  offerBottomRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  offerFooterText: {
    fontFamily,
    fontSize: 13,
    fontWeight: '700',
  },
  offerRatingRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    flexWrap: 'wrap',
  },
  smallAction: {
    minHeight: 40,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  smallActionText: {
    fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  clubInfoGrid: {
    flexDirection: 'row-reverse',
    gap: 10,
    marginTop: 16,
  },
  clubInfoBox: {
    flex: 1,
    minHeight: 98,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  clubInfoLabel: {
    textAlign: 'right',
    fontFamily,
    fontSize: 13,
    fontWeight: '600',
  },
  clubInfoValue: {
    marginTop: 10,
    textAlign: 'right',
    fontFamily,
    fontSize: 18,
    fontWeight: '900',
  },
  clubInfoHint: {
    marginTop: 4,
    textAlign: 'right',
    fontFamily,
    fontSize: 13,
    fontWeight: '700',
  },
  clubFooter: {
    marginTop: 14,
    gap: 10,
  },
  clubFooterActions: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  clubActionGroup: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  clubActionButton: {
    minHeight: 38,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  clubActionText: {
    fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  clubManagerRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
  },
  clubTopRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 14,
  },
  clubIdentityWrap: {
    flex: 1,
    alignItems: 'flex-end',
    paddingTop: 2,
  },
  clubStatusPill: {
    minHeight: 32,
    borderRadius: 999,
    paddingHorizontal: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 4,
  },
  clubStatusText: {
    fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  clubManagerText: {
    fontFamily,
    fontSize: 13,
    fontWeight: '700',
  },
  clubMetaDot: {
    fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  renewButton: {
    minHeight: 48,
    borderRadius: 20,
    paddingHorizontal: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  renewButtonText: {
    fontFamily,
    fontSize: 12,
    fontWeight: '800',
    flexShrink: 1,
  },
  clubRenewButton: {
    minHeight: 40,
    borderRadius: 18,
    paddingHorizontal: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chartTitleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  chartTitle: {
    fontFamily,
    fontSize: 18,
    fontWeight: '900',
  },
  chartHint: {
    fontFamily,
    fontSize: 13,
    fontWeight: '600',
  },
  chartBody: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    flex: 1,
    marginTop: 22,
  },
  chartColumn: {
    flex: 1,
    alignItems: 'center',
    gap: 10,
  },
  chartBarWrap: {
    height: 122,
    justifyContent: 'flex-end',
  },
  chartBar: {
    width: 18,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  chartDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    marginTop: -6,
  },
  chartLabel: {
    fontFamily,
    fontSize: 12,
    fontWeight: '700',
  },
  chipWrap: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  chipButton: {
    minHeight: 38,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  chipText: {
    fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
});
