import { StyleSheet } from 'react-native';

import {
  Colors,
  Dimensions,
  FontFamily,
  FontSize,
  FontWeight,
  SemanticColors,
} from '@src/styles/ui-theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    overflow: 'hidden',
  },
  softOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(244, 245, 250, 0.84)',
  },
  topRightBubble: {
    position: 'absolute',
    top: -120,
    right: -90,
    width: 360,
    height: 360,
    borderRadius: Dimensions.radiusFull,
    backgroundColor: 'rgba(104, 140, 245, 0.21)',
  },
  topLeftBubble: {
    position: 'absolute',
    top: 320,
    left: -130,
    width: 250,
    height: 250,
    borderRadius: Dimensions.radiusFull,
    backgroundColor: 'rgba(124, 156, 251, 0.1)',
  },
  content: {
    flex: 1,
    paddingHorizontal: 26,
    zIndex: 2,
    alignItems: 'center',
  },
  backButton: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 16,
    gap: 2,
    paddingHorizontal: 4,
    minHeight: 26,
  },
  backButtonText: {
    color: Colors.primary,
    fontFamily: FontFamily.cairo,
    fontSize: 18 / 2,
    fontWeight: FontWeight.semibold,
  },
  logoBox: {
    width: 80,
    height: 80,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 6,
  },
  formArea: {
    width: '100%',
    maxWidth: 390,
    marginTop: 26,
    gap: 12,
  },
  title: {
    color: Colors.foreground,
    fontFamily: FontFamily.cairo,
    fontSize: 44 / 2,
    fontWeight: FontWeight.bold,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  subtitle: {
    color: Colors.mutedForeground,
    fontFamily: FontFamily.cairo,
    fontSize: 30 / 2,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 16,
  },
  subtitleCompact: {
    color: Colors.mutedForeground,
    fontFamily: FontFamily.cairo,
    fontSize: 30 / 2,
    textAlign: 'center',
    marginTop: -4,
  },
  emailText: {
    color: Colors.primary,
    fontFamily: FontFamily.cairo,
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    textAlign: 'center',
    marginBottom: 24,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 16,
    minHeight: 56,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  input: {
    flex: 1,
    color: Colors.foreground,
    fontFamily: FontFamily.cairo,
    fontSize: FontSize.md,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  trailingIconButton: {
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hintBox: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 13,
    backgroundColor: Colors.secondary,
    marginBottom: 8,
  },
  hintDot: {
    width: 6,
    height: 6,
    borderRadius: Dimensions.radiusFull,
    backgroundColor: Colors.primary,
  },
  hintText: {
    flex: 1,
    color: Colors.primary,
    textAlign: 'right',
    writingDirection: 'rtl',
    fontFamily: FontFamily.cairo,
    fontSize: 12,
    lineHeight: 18,
  },
  codeRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 12,
  },
  codeInput: {
    width: 46,
    height: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
    color: Colors.foreground,
    fontFamily: FontFamily.cairo,
    fontSize: FontSize.lg,
    textAlign: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
  },
  successIconCircle: {
    width: 90,
    height: 90,
    borderRadius: Dimensions.radiusFull,
    backgroundColor: `${SemanticColors.green}2E`,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 14,
  },
  primaryButton: {
    marginTop: 8,
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 5,
  },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: FontFamily.cairo,
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
  },
  secondaryButtonText: {
    color: Colors.foreground,
    fontFamily: FontFamily.cairo,
    fontSize: FontSize.base,
    fontWeight: FontWeight.semibold,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  buttonPressed: {
    transform: [{ scale: 0.985 }],
  },
  buttonDisabled: {
    opacity: 0.75,
  },
  errorText: {
    color: Colors.destructive,
    textAlign: 'right',
    writingDirection: 'rtl',
    fontFamily: FontFamily.cairo,
    fontSize: FontSize.sm,
    marginTop: -2,
  },
});
