import { getAvatarColor, getAvatarInitial } from '@/components/chat/chat-ui';
import { getRoleOption } from '@/lib/admin/admin-config';
import type {
  AdminClubItem,
  AdminClubSummary,
  AdminDashboardSummary,
  AdminNewsItem,
  AdminOfferItem,
  AdminRoleMember,
  AdminRoleScopeOption,
  AdminRoleSummary,
  AdminUser,
} from '@/types/admin';

function buildAvatar(name: string) {
  return {
    avatarInitial: getAvatarInitial(name),
    avatarColor: getAvatarColor(name),
  };
}

export const adminDashboardFixture: AdminDashboardSummary = {
  usersCount: 1248,
  adsCount: 356,
  messagesCount: 2400,
  usersGrowth: 12,
  adsGrowth: 8,
  messagesGrowth: 18,
  activityWindowLabel: 'آخر 7 أيام',
  activityPoints: [
    { label: 'سبت', value: 42 },
    { label: 'أحد', value: 56 },
    { label: 'إثن', value: 48 },
    { label: 'ثلا', value: 63 },
    { label: 'أرب', value: 58 },
    { label: 'خمي', value: 71 },
    { label: 'جمع', value: 67 },
  ],
};

export const adminUsersFixture: AdminUser[] = [
  {
    id: 'u-1',
    fullName: 'أحمد محمد',
    email: 'ahmed@ju.edu.jo',
    universityId: 1,
    universityName: 'الجامعة الأردنية',
    postsCount: 12,
    status: 'active',
    joinedAt: '2026-01-12',
    ...buildAvatar('أحمد محمد'),
  },
  {
    id: 'u-2',
    fullName: 'سارة علي',
    email: 'sara@just.edu.jo',
    universityId: 2,
    universityName: 'جامعة العلوم والتكنولوجيا',
    postsCount: 8,
    status: 'active',
    joinedAt: '2026-01-18',
    ...buildAvatar('سارة علي'),
  },
  {
    id: 'u-3',
    fullName: 'محمد خالد',
    email: 'mohammed@hu.edu.jo',
    universityId: 3,
    universityName: 'الجامعة الهاشمية',
    postsCount: 3,
    status: 'blocked',
    joinedAt: '2026-01-20',
    ...buildAvatar('محمد خالد'),
  },
  {
    id: 'u-4',
    fullName: 'لينا حسن',
    email: 'lina@yu.edu.jo',
    universityId: 4,
    universityName: 'جامعة اليرموك',
    postsCount: 15,
    status: 'active',
    joinedAt: '2026-01-22',
    ...buildAvatar('لينا حسن'),
  },
  {
    id: 'u-5',
    fullName: 'عمر أحمد',
    email: 'omar@ju.edu.jo',
    universityId: 1,
    universityName: 'الجامعة الأردنية',
    postsCount: 6,
    status: 'active',
    joinedAt: '2026-02-05',
    ...buildAvatar('عمر أحمد'),
  },
];

export const adminNewsFixture: AdminNewsItem[] = [
  {
    id: 'n-1',
    title: 'بيت نالو',
    content: 'تتنافس معهم يختلف الأمر هناك',
    source: 'بيتانبلر',
    category: 'منح وبعثات',
    imageUrl: null,
    isImportant: true,
    isPublished: false,
    viewsCount: 0,
    createdAt: '2026-04-01T09:00:00.000Z',
    createdAtLabel: '2026-04-01',
    status: 'draft',
  },
  {
    id: 'n-2',
    title: 'تأجيل امتحانات الفصل الأول أسبوعاً كاملاً',
    content: 'تم تأجيل جميع امتحانات الفصل الأول أسبوعاً كاملاً بسبب الأحوال الجوية.',
    source: 'عمادة شؤون الطلبة',
    category: 'إعلان عام',
    imageUrl: null,
    isImportant: false,
    isPublished: true,
    viewsCount: 1240,
    createdAt: '2026-02-25T08:00:00.000Z',
    createdAtLabel: '2026-02-25',
    status: 'published',
  },
  {
    id: 'n-3',
    title: 'فتح باب التسجيل للفصل الصيفي 2026',
    content: 'يبدأ التسجيل الإلكتروني اعتباراً من الأسبوع المقبل عبر بوابة الطالب.',
    source: 'دائرة القبول والتسجيل',
    category: 'أكاديمي',
    imageUrl: null,
    isImportant: false,
    isPublished: true,
    viewsCount: 890,
    createdAt: '2026-02-24T08:00:00.000Z',
    createdAtLabel: '2026-02-24',
    status: 'published',
  },
  {
    id: 'n-4',
    title: 'منح دراسية جديدة متاحة للطلبة المتفوقين',
    content: 'تم إطلاق مجموعة منح جديدة للطلبة المتفوقين في عدد من التخصصات.',
    source: 'شؤون المنح',
    category: 'منح وبعثات',
    imageUrl: null,
    isImportant: false,
    isPublished: false,
    viewsCount: 0,
    createdAt: '2026-02-26T08:00:00.000Z',
    createdAtLabel: '2026-02-26',
    status: 'draft',
  },
];

export const adminRoleScopeFixture: AdminRoleScopeOption[] = [
  { id: 1, name: 'ورشة عمل البرمجة بالبايثون' },
  { id: 2, name: 'معرض الكتب المستعملة' },
  { id: 3, name: 'محاضرة ريادة الأعمال' },
  { id: 4, name: 'يوم الأمن الجامعي' },
];

export const adminRolesFixture: AdminRoleMember[] = [
  {
    id: 'role-1',
    fullName: 'أحمد محمد',
    email: 'ahmed@ju.edu.jo',
    role: 'admin',
    scopeId: null,
    scopeName: null,
    permissions: getRoleOption('admin').permissions,
    addedAt: '2026-01-10',
    addedBy: 'المدير الأعلى',
    ...buildAvatar('أحمد محمد'),
  },
  {
    id: 'role-2',
    fullName: 'لينا حسن',
    email: 'lina@ju.edu.jo',
    role: 'eventOwner',
    scopeId: 1,
    scopeName: 'ورشة عمل البرمجة بالبايثون',
    permissions: getRoleOption('eventOwner').permissions,
    addedAt: '2026-01-18',
    addedBy: 'المدير الأعلى',
    ...buildAvatar('لينا حسن'),
  },
  {
    id: 'role-3',
    fullName: 'عمر أحمد',
    email: 'omar@ju.edu.jo',
    role: 'eventOwner',
    scopeId: null,
    scopeName: null,
    permissions: getRoleOption('eventOwner').permissions,
    addedAt: '2026-01-20',
    addedBy: 'أحمد محمد',
    ...buildAvatar('عمر أحمد'),
  },
];

export const adminRoleSummaryFixture: AdminRoleSummary[] = [
  { role: 'admin', count: 1 },
  { role: 'superAdmin', count: 0 },
  { role: 'eventOwner', count: 2 },
];

export const adminOffersFixture: AdminOfferItem[] = [
  {
    id: 'offer-1',
    imageUrl: null,
    partnerName: 'أكاديمية كود تك',
    type: 'academy',
    category: 'برمجة',
    title: 'خصم %40 على دورة Flutter',
    description: 'دورة شاملة لتطوير تطبيقات الجوال بلغة Flutter - مدة 3 أشهر',
    location: 'عمان - شارع الجامعة',
    phone: '0791234567',
    email: 'info@codetech.jo',
    expireDateUtc: '2026-04-01T00:00:00.000Z',
    discountPercent: 40,
    showOnHomePage: true,
    isVerified: true,
    viewsCount: 124,
    rating: 4.8,
    ratingsCount: 124,
  },
  {
    id: 'offer-2',
    imageUrl: null,
    partnerName: 'مكتبة النجاح',
    type: 'store',
    category: 'كتب',
    title: 'خصم %25 على الكتب الجامعية',
    description: 'عروض خاصة على كتب الهندسة والعلوم طوال شهر مارس',
    location: 'إربد - قرب البوابة الرئيسية',
    phone: '0781112233',
    email: 'books@najah.jo',
    expireDateUtc: '2026-03-28T00:00:00.000Z',
    discountPercent: 25,
    showOnHomePage: true,
    isVerified: true,
    viewsCount: 93,
    rating: 4.6,
    ratingsCount: 57,
  },
  {
    id: 'offer-3',
    imageUrl: null,
    partnerName: 'بيت نالو',
    type: 'academy',
    category: 'برمجة',
    title: 'خصم %15 على كورسات الذكاء الاصطناعي',
    description: 'عرض خاص لطلبة الجامعات على باقات التدريب المسائية.',
    location: 'نابلس - شارع الجامعة',
    phone: '057637833',
    email: 's12325356@stu.najah.edu',
    expireDateUtc: '2026-11-11T00:00:00.000Z',
    discountPercent: 15,
    showOnHomePage: false,
    isVerified: false,
    viewsCount: 0,
    rating: 0,
    ratingsCount: 0,
  },
];

export const adminClubsFixture: AdminClubItem[] = [
  {
    id: 'club-1',
    name: 'نادي البرمجة',
    universityName: 'الجامعة الأردنية',
    managerName: 'أحمد خالد',
    managerEmail: 'prog@ju.edu.jo',
    subscriptionType: 'yearly',
    status: 'active',
    startedAt: '2026-01-01',
    expiresAt: '2026-12-31',
    priceLabel: '120 د.ا',
    ...buildAvatar('نادي البرمجة'),
  },
  {
    id: 'club-2',
    name: 'نادي ريادة الأعمال',
    universityName: 'الجامعة الأردنية',
    managerName: 'سارة عمر',
    managerEmail: 'biz@ju.edu.jo',
    subscriptionType: 'monthly',
    status: 'expiring',
    startedAt: '2026-02-01',
    expiresAt: '2026-03-05',
    priceLabel: '15 د.ا',
    ...buildAvatar('نادي ريادة الأعمال'),
  },
  {
    id: 'club-3',
    name: 'نادي الفنون',
    universityName: 'جامعة العلوم والتكنولوجيا',
    managerName: 'ملك حسين',
    managerEmail: 'art@just.edu.jo',
    subscriptionType: 'monthly',
    status: 'expired',
    startedAt: '2026-01-10',
    expiresAt: '2026-02-10',
    priceLabel: '15 د.ا',
    ...buildAvatar('نادي الفنون'),
  },
  {
    id: 'club-4',
    name: 'مجلس الطلبة',
    universityName: 'الجامعة الهاشمية',
    managerName: 'عمر فارس',
    managerEmail: 'council@hu.edu.jo',
    subscriptionType: 'yearly',
    status: 'active',
    startedAt: '2026-01-15',
    expiresAt: '2027-01-15',
    priceLabel: '120 د.ا',
    ...buildAvatar('مجلس الطلبة'),
  },
];

export const adminClubSummaryFixture: AdminClubSummary = {
  active: 2,
  expiring: 1,
  expired: 1,
};
